#!/usr/bin/env zsh

function lsd_with_hint() {
    /usr/bin/lsd "$@"
    if /usr/bin/lsd -1 "$@" 2>/dev/null | grep -qE '\.(jpg|jpeg|png|gif|bmp|tiff|webp|svg)$'; then
        echo "Hint: 'lsix' to see image thumbnails"
    fi
}

alias -g ls="lsd_with_hint"
alias -g cat="bat"
alias -g man="batman"
alias -g pretty="prettybat"
alias -g ip="ip -c"
