#!/usr/bin/env zsh
# PATH: auto-dedupe, prepend user-local dirs

typeset -U path PATH

path=(
  "$HOME/.local/bin"
  "$HOME/.npm-global/bin"
  "$HOME/go/bin"
  "$HOME/.cargo/bin"
  $path
)

export GOPATH="$HOME/go"
